[package]
name = "kuavo_humanoid_rust_sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
rosrust = "0.9"
rosrust_msg = "0.1"

# tokio may be needed for async operations in the future
# tokio = { version = "1.39.0", features = ["full"] }